# Premier pas avec Pandas

Pandas est un module destiné à la manipulation de données. Il a été créé en 2008 et est très activement développé depuis. Il a été conçu au départ pour l’analyse de données financières.

On l’importe comme n’importe quel module, et l’usage est de l’abrévier en «pd», grâce au mot-clé `as`:

In [4]:
import pandas as pd

Dans Excel, on parle de «feuilles de calcul». L’équivalent, dans Pandas, est un **DataFrame**, qu’on abrège **df**.

Pour vous familiariser avec cet objet, on va ouvrir [des données de l’OFS obtenues sur STAT-TAB](http://www.pxweb.bfs.admin.ch/sq/a39f8d09-9e2b-4a58-b67a-51d22ebbe989):

In [5]:
df = pd.read_csv('couts-personnel-hautes-ecoles.csv')

Voyons à quoi ressemblent les 5 premières lignes

In [6]:
df.head()

,Année,Prestation,Nature de coûts,HETS-GE,HEP-BEJUNE,HEP-VD,HEP-VS,HEP-FR
0,2009,Enseignement de base,Personnel,1845950,11603840,22487075,7449804,7679101
1,2009,Recherche appliquée et développement,Personnel,174791,1254804,4998217,1163338,1655812
2,2009,Formation continue,Personnel,137429,3937666,6571043,538089,1681846
3,2009,Prestations de services,Personnel,133224,1431853,2123045,0,3767684
4,2010,Enseignement de base,Personnel,1787920,14031903,20368249,7553247,9476562

## Filtrer

Regardons maintenant l’année 2019. Avec Pandas, ça se fait comme suit:

In [8]:
df[ df['Année'] == 2019 ]

,Année,Prestation,Nature de coûts,HETS-GE,HEP-BEJUNE,HEP-VD,HEP-VS,HEP-FR
40,2019,Enseignement de base,Personnel,1994090,12553917,43207376,9054637,9650727
41,2019,Recherche appliquée et développement,Personnel,235679,2176814,12663265,1972288,2079828
42,2019,Formation continue,Personnel,494971,3874482,8691043,1661413,2018726
43,2019,Prestations de services,Personnel,520148,2349377,2639705,2676579,1724585

In [10]:
df[ df['HETS-GE'] < 100000 ]

,Année,Prestation,Nature de coûts,HETS-GE,HEP-BEJUNE,HEP-VD,HEP-VS,HEP-FR
11,2011,Prestations de services,Personnel,81651,1443942,1683585,0,3260529
23,2014,Prestations de services,Personnel,96074,1429297,1377381,3015743,2972196
27,2015,Prestations de services,Personnel,86708,1349543,1569324,2892061,3040953

Autrement dit: on a demandé «Montre moi le dataframe pour lequel la colonne «Année» est égale à 2019».

On peut choisir d’afficher uniquement certaines colonnes. Pour ce faire, on utilise une liste:

In [12]:
columnsToShow = ['Année', 'HEP-VD', 'HEP-FR']

In [20]:
test = list(df.columns)

In [22]:
test.remove('HEP-VD')

In [23]:
df[ test ]

,Année,Prestation,Nature de coûts,HETS-GE,HEP-BEJUNE,HEP-VS,HEP-FR
0,2009,Enseignement de base,Personnel,1845950,11603840,7449804,7679101
1,2009,Recherche appliquée et développement,Personnel,174791,1254804,1163338,1655812
2,2009,Formation continue,Personnel,137429,3937666,538089,1681846
3,2009,Prestations de services,Personnel,133224,1431853,0,3767684
4,2010,Enseignement de base,Personnel,1787920,14031903,7553247,9476562
5,2010,Recherche appliquée et développement,Personnel,149512,1502861,967376,1042346
6,2010,Formation continue,Personnel,146551,3804777,1809025,1295660
7,2010,Prestations de services,Personnel,100169,1419544,0,3133284
8,2011,Enseignement de base,Personnel,1821890,14199474,8023424,9812603
9,2011,Recherche appliquée et développement,Personnel,228251,1537543,968652,1208909
10,2011,Formation continue,Personnel,133821,4066746,1877448,1275166
11,2011,Prestations de services,Personnel,81651,1443942,0,3260529
12,2012,Enseignement de base,Personnel,1879788,13825057,8453706,10184870
13,2012,Recherche appliquée et développement,Personnel,254828,1551007,953634,1162974
14,2012,Formation continue,Personnel,161025,5179649,1746074,1330662
15,2012,Prestations de services,Personnel,119333,1457441,0,3379067
16,2013,Enseignement de base,Personnel,2051730,13420288,8342866,9933486
17,2013,Recherche appliquée et développement,Personnel,218472,1795335,1014555,1137709
18,2013,Formation continue,Personnel,193299,4876828,1886098,1982338
19,2013,Prestations de services,Personnel,121384,1469451,0,3172321
20,2014,Enseignement de base,Personnel,2122376,12717387,8458984,9638424
21,2014,Recherche appliquée et développement,Personnel,257229,1914540,925649,1261784
22,2014,Formation continue,Personnel,160397,5048905,1706339,1917978
23,2014,Prestations de services,Personnel,96074,1429297,3015743,2972196
24,2015,Enseignement de base,Personnel,2080177,13244598,8037192,9517863
25,2015,Recherche appliquée et développement,Personnel,305237,1898223,942902,1270509
26,2015,Formation continue,Personnel,223118,4967718,1693342,1761967
27,2015,Prestations de services,Personnel,86708,1349543,2892061,3040953
28,2016,Enseignement de base,Personnel,2078340,12929548,7985699,9823898
29,2016,Recherche appliquée et développement,Personnel,385855,2012681,1216698,1163407
30,2016,Formation continue,Personnel,314951,4968285,1693019,1915273
31,2016,Prestations de services,Personnel,301265,1646523,2657838,1687785
32,2017,Enseignement de base,Personnel,1977361,13338050,8059686,9600105
33,2017,Recherche appliquée et développement,Personnel,275926,2164651,1465795,1168407
34,2017,Formation continue,Personnel,341191,3358434,1674016,1962059
35,2017,Prestations de services,Personnel,405726,1781042,2555640,1689654
36,2018,Enseignement de base,Personnel,1932761,13542045,8633675,9564308
37,2018,Recherche appliquée et développement,Personnel,256710,2238965,1787200,2118586
38,2018,Formation continue,Personnel,154446,3499772,1666031,1797675
39,2018,Prestations de services,Personnel,199456,1744989,2408620,1707231
40,2019,Enseignement de base,Personnel,1994090,12553917,9054637,9650727
41,2019,Recherche appliquée et développement,Personnel,235679,2176814,1972288,2079828
42,2019,Formation continue,Personnel,494971,3874482,1661413,2018726
43,2019,Prestations de services,Personnel,520148,2349377,2676579,1724585

In [24]:
df['Prestation'].value_counts()

Formation continue                      11
Enseignement de base                    11
Recherche appliquée et développement    11
Prestations de services                 11
Name: Prestation, dtype: int64

Mettons qu’on s’intéresse uniquement à 2019 et aux montants supérieurs à zéro, à l’IHEID…

In [22]:
df[ (df['Année'] == 2019) & (df['IHEID'] > 0) ]

TypeError: '>' not supported between instances of 'str' and 'int'

Que s’est-il passé? Pas de panique. On a déjà vu ce genre de trucs. Python nous dit qu’on ne peut pas comparer un "string" et un "integer" avec l’opérateur ">". Ça signifie que soit le chiffre 0, soit la colonne IHEID n’est pas un entier.

Voyons si on peut regarder cette colonne de plus près.

In [27]:
df['IHEID'].values

array(['...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '...',
       '...', '...', '...', '...', '...', '...', '...', '...', '5909076',
       '8546304', '15188806', '0', '765055', '0', '0', '0', '0',
       '1254536', '0', '0', '18500000', '0', '3059864', '0', '0',
       '4536939', '0', '1983224', '1363111', '7506022', '0', '0', '0',
       '0', '7825144', '364608', '3094066', '4887775', '0', '0', '0', '0',
       '0', '0', '0', '0', '6049912', '8299313', '14895798', '0',
       '614280', '0', '0', '0', '0', '1441445', '0', '0', '18326379', '0',
       '4082757', '0', '0', '5094757', '0', '3169765', '1045514',
       '6963630', '0', '0', '0', '0', '8165249', '867271', '2500620',
       '5402363', '0', '0', '0', '0', '0', '0', '0', '0', '6577521',
       '7932563', '15036918', '0', '739350', '0', '0', '0', '0',
       '1447556', '0', '0', '18000000', '0', '2270050', '0', '0',
       '7701050', '0', '2548090', '799482', '5881122', '0', '0', '0', '0',
       '7291259', '1547700', '3520963', '5554512', '0', '0', '0', '0',
       '0', '0', '0', '0'], dtype=object)

Aïe. Le fichier de l’OFS contient des "…". Ce n’est pas un entier, du coup Pandas considère toute cette colonne comme du texte et notre erreur vient de là.

On abandonne l’IHEID et on va regarder l’UNIGE. Ça devrait marcher:

In [32]:
df['GE'].values

array([  3400000,   7710000, 279440000,   1958000,  22358000,         0,
               0,         0,         0,         0,         0,         0,
        69733000,         0,         0,         0,         0,  45540000,
               0,         0,         0,         0,         0,         0,
               0,         0,         0,         0,         0,         0,
               0,         0,         0,         0,         0,         0,
        -7881000,  80741000,  10094425,   7594914, 301109420,     90000,
        22863256,   9502309,         0,         0,         0,         0,
               0, -28180000,  62125676,         0,         0,         0,
        -2579000,  47359250,         0,         0,     50873,         0,
               0,   4821991,         0,         0,         0,         0,
               0,         0,       500,         0,         0,  48466520,
               0,   4097422,  -7488000,  23555130,   8297000,         0,
       301295000,         0,  22880000,         0,   7823000,         0,
               0,         0,         0,  -6455000,  59004000,         0,
               0,         0,         0,  47223000,         0,         0,
               0,         0,         0,         0,         0,         0,
               0,         0,         0,         0,         0,         0,
               0,  53752000,  10380000,         0,         0,         0,
         8450758,  20799068, 289800002,         0,  23712124,         0,
         9807114,         0,         0,         0,         0,         0,
        59522311,         0,         0,         0,         0,  47816906,
               0,         0,         0,         0,         0,         0,
               0,         0,         0,         0,         0,         0,
               0,         0,         0,  69627060,         0,         0,
               0,         0,   8649000,  15191253, 289974095,         0,
        26872107,         0,   4592328,         0,         0,         0,
               0,         0,  60842582,         0,         0,         0,
               0,  47036734,         0,         0,         0,         0,
               0,         0,         0,         0,         0,         0,
               0,         0,         0,         0,         0,  75861869,
               0,         0,         0,         0,   8832451,   6164034,
       298838901,         0,  28841979,     99306,   1498790,   2881681,
         4071532,     81656,         0,         0,  59807501,         0,
               0,         0,         0,  44870699,    939827,   6328023,
         3701365,   7924929,         0,         0,         0,         0,
        38455703,   6983157,  12376043,   8397170,         0,         0,
               0,         0,         0,         0,         0,         0,
         9012422,   6150916, 318365110,         0,  29115245,     99400,
         1567513,   5153868,   2708696,     14003,         0,         0,
        59346243,         0,         0,         0,         0,  47483722,
         1206730,   7239139,   4213474,  10420585,         0,         0,
               0,         0,  48820076,   9651413,  12856270,  14388983,
               0,         0,         0,         0,         0,         0,
               0,         0,   8908105,   7704214, 324545634,         0,
        28440736,     74369,   2412262,    742743,   6620073,         0,
               0,         0,  63156595,         0,         0,         0,
               0,  54586523,   1356301,   7997521,   2666560,  14622420,
               0,         0,         0,         0,  40598380,  25100154,
        11237449,  10186528,         0,         0,         0,         0,
               0,         0,         0,         0,   9875469,   8471332,
       345876851,         0,  29609452,    196090,   2171098,    455488,
         5866127,         0,         0,         0,  70961734,         0,
               0,         0,         0,  58352912,   2259899,   7658509,
         1332352,  16577541,         0,         0,         0,         0,
        37971551,  17321047,  11985048,  10759401,         0,         0,
               0,         0,         0,         0,         0,         0,
        11623824,  10874198, 344869190,         0,  28729712,    285126,
         4263418,   3286594,   4199391,         0,         0,         0,
        75006225,         0,         0,         0,         0,  60679413,
         1960908,   8436403,    880863,  11195813,         0,         0,
               0,         0,  32998346,  14171250,  10062573,   8873525,
               0,         0,         0,         0,         0,         0,
               0,         0,  12519075,  13332943, 356500422,         0,
        30181395,    133034,    390202,   4009043,   2391202,         0,
               0,         0,  80731634,         0,         0,         0,
               0,  61370935,   1099338,   8861700,    903753,   9978003,
               0,         0,         0,         0,  30739179,  13759464,
        10028391,   9782631,         0,         0,         0,         0,
               0,         0,         0,         0,  11430587,  16108811,
       313768536,         0,  30050130,     58335,   2549095,   3521473,
          124551,         0,         0,         0,  77121019,         0,
               0,         0,         0,  55249911,    539875,   9703763,
          965029,   9794631,         0,         0,         0,         0,
        31979869,  14352604,  19084228,   9957745,         0,         0,
               0,         0,         0,         0,         0,         0,
        10853905,  12507352, 349216914,         0,  20138651,     65969,
         1959607,   3240802,    410884,         0,         0,         0,
        70451201,         0,         0,         0,         0,  58154475,
          649241,  12500245,    788543,   9598055,         0,         0,
               0,         0,  35330607,  20778415,  23953619,  11526826,
               0,         0,         0,         0,         0,         0,
               0,         0,  11753651,  18042106, 444431361,         0,
        19680963,   5009378,         0,    778066,         0,         0,
               0,         0,  80530056,         0,         0,         0,
               0,  63703378,   1017865,  14598768,   1416307,  11234780,
               0,         0,         0,         0,  42587936,  47843464,
        26086938,  12432487,         0,         0,         0,         0,
               0,         0,         0,         0,  12532043,  19019650,
       434081061,         0,  19759974,   5106220,         0,         0,
               0,         0,         0,         0,  84534488,         0,
               0,         0,         0,  67115882,   1409609,  17323743,
         2049221,   8442871,         0,         0,         0,         0,
        32561429,  27872212,  34516863,  13966924,         0,         0,
               0,         0,         0,         0,         0,         0,
        13611881,  18843926, 396496275,         0,  21932930,   5106220,
               0,   5859823,   2000000,         0,         0,         0,
        98972679,         0,         0,         0,         0,  70939369,
         1669775,  17924307,   2565595,  21687274,         0,         0,
               0,         0,  26673199,  22733075,  41039411,  12873352,
               0,         0,         0,         0,         0,         0,
               0,         0,  13696989,  18209826, 399153072,         0,
        22125830,   5119426,         0,   6597236,   2000000,         0,
               0,         0,  98274478,         0,         0,         0,
               0,  79860714,    799307,  22879649,   4815645,  21301989,
               0,         0,         0,         0,  34462227,  11412191,
        37545270,  13636295,         0,         0,         0,         0,
               0,         0,         0,         0,  15176900,  16804777,
       401783823,         0,  21009998,   5093014,         0,    564736,
               0,         0,         0,         0, 106827904,         0,
         1064202,         0,         0,  80178281,   1290019,  17544117,
         2629910,  21106928,         0,         0,         0,         0,
        35303449,   8120878,  61667151,  15505515,         0,         0,
               0,         0,         0,         0,         0,         0,
        16738369,  18212214, 406880318,         0,  18331082,   5071005,
               0,    335720,         0,   1019095,         0,         0,
       108592776,         0,   1107626,         0,         0,  83927097,
         2194038,  20918138,   5419069,  18383380,         0,         0,
               0,         0,  31754854,  11220063,  61411932,  19023777,
               0,         0,         0,         0,         0,         0,
               0,         0,  17005401,  19465955, 322202111,         0,
        34173270,   5075407,         0,   -450575,         0,    999617,
               0,         0, 110461024,         0,   1727420,         0,
               0,  81534125,   2191693,  20805779,   6083297,  17734031,
               0,         0,         0,         0,  32909938,  10230747,
        65790621,  18931187,         0,         0,         0,         0,
               0,         0,         0,         0,  18564487,  21391622,
       354260330,         0,  33645559,   5075407,         0,   -337451,
               0,   2364031,         0,         0, 113369508,         0,
          967241,    314188,         0,  83212575,   2591588,  19670004,
         4458286,  19606737,         0,         0,         0,    126366,
        32182365,  14750666,  76427857,  16770387,         0,         0,
               0,         0,         0,         0,         0,         0,
        18260089,  24486598, 353896648,         0,  34784336,   5004976,
               0,    528502,         0,   1254264,         0,         0,
       115425894,         0,   2816201,   1363517,         0,  86107033,
         2418655,  15362909,   4634805,  18430549,         0,         0,
               0,    648242,  32131709,  16383461,  80843664,  16239094,
               0,         0,         0,         0,         0,         0,
               0,         0,  13159095,  18747308, 331316549,         0,
        35790536,   4987368,         0,   1041737,         0,         0,
               0,         0, 105131579,         0,         0,   1444760,
               0,  86752318,   3051492,  11953963,   3869140,  10236458,
               0,         0,         0,   2194982,  23220977,  13479733,
        81517445,  11547330,         0,         0,         0,         0,
               0,         0,         0,         0,  13233857,  18232436,
       337499150,         0,  38012008,   5026986,    445584,    750673,
               0,         0,         0,         0, 108007473,         0,
               0,   1601014,         0,  87111302,   2801158,  11514399,
         3824928,   9318584,         0,         0,         0,   2182867,
        22319866,  11115838,  84464418,  12574385,         0,         0,
               0,         0,         0,         0,         0,         0,
        13580478,  20205526, 370732623,         0,  37795445,   2625808,
          448785,    739396,         0,         0,         0,         0,
       110890055,         0,         0,   1918653,         0,  85110337,
         2866273,  12979363,   2639115,  12662390,         0,         0,
               0,   1739988,  24933883,  12112604,  80459268,  13551495,
               0,         0,         0,         0,         0,         0,
               0,         0])

On redéfinit nos colonnes à afficher:

In [35]:
columnsToShow = ['Source de financement', 'GE']
df[ (df['Année'] == 2019) & (df['GE'] > 0) ][columnsToShow]

                                 Source de financement         GE
912                                            Ecolage   13580478
913            Autres moyens propres de la haute école   20205526
914         Canton universitaire: couverture ou budget  370732623
916  Autres cantons: accord intercantonal universit...   37795445
917                 Autres cantons: autres subventions    2625808
918  Confédération: contributions aux investissemen...     448785
919  Confédération: contributions liées à des proje...     739396
924  Confédération: subventions de base LEHE (autre...  110890055
927  Financement de projets de l'UE par le FNS (dès...    1918653
929                                     Projets du FNS   85110337
930              Projets de Innosuisse (autrefois CTI)    2866273
931                    Programmes de recherche de l'UE   12979363
932                   Autres programmes internationaux    2639115
933           Mandats de recherche de la Confédération   12662390
937        Financement de projets de l'UE par le SEFRI    1739988
938              Mandats de recherche du secteur privé   24933883
939  Mandats de recherche des autres collectivités ...   12112604
940                 Revenus des prestations de service   80459268
941                   Revenus de la formation continue   13551495

## Trier
Dans Pandas, le tri se fait avec la méthode `.sort_values("nom_colonne_ici")`.

Mais commençons par enregistrer les données genevoises dans une variable, on gagnera du temps…

In [39]:
df_GE = df[ (df['Année'] == 2019) & (df['GE'] > 0) ][columnsToShow]

In [40]:
df_GE.sort_values('GE')

                                 Source de financement         GE
918  Confédération: contributions aux investissemen...     448785
919  Confédération: contributions liées à des proje...     739396
937        Financement de projets de l'UE par le SEFRI    1739988
927  Financement de projets de l'UE par le FNS (dès...    1918653
917                 Autres cantons: autres subventions    2625808
932                   Autres programmes internationaux    2639115
930              Projets de Innosuisse (autrefois CTI)    2866273
939  Mandats de recherche des autres collectivités ...   12112604
933           Mandats de recherche de la Confédération   12662390
931                    Programmes de recherche de l'UE   12979363
941                   Revenus de la formation continue   13551495
912                                            Ecolage   13580478
913            Autres moyens propres de la haute école   20205526
938              Mandats de recherche du secteur privé   24933883
916  Autres cantons: accord intercantonal universit...   37795445
940                 Revenus des prestations de service   80459268
929                                     Projets du FNS   85110337
924  Confédération: subventions de base LEHE (autre...  110890055
914         Canton universitaire: couverture ou budget  370732623

Que s’est-il passé? Par défaut, Pandas trie par ordre ascendant. Pour obtenir l’inverse, il faut préciser `ascending=False`:

In [43]:
df_GE = df_GE.sort_values('GE', ascending=False)
df_GE

                                 Source de financement         GE
914         Canton universitaire: couverture ou budget  370732623
924  Confédération: subventions de base LEHE (autre...  110890055
929                                     Projets du FNS   85110337
940                 Revenus des prestations de service   80459268
916  Autres cantons: accord intercantonal universit...   37795445
938              Mandats de recherche du secteur privé   24933883
913            Autres moyens propres de la haute école   20205526
912                                            Ecolage   13580478
941                   Revenus de la formation continue   13551495
931                    Programmes de recherche de l'UE   12979363
933           Mandats de recherche de la Confédération   12662390
939  Mandats de recherche des autres collectivités ...   12112604
930              Projets de Innosuisse (autrefois CTI)    2866273
932                   Autres programmes internationaux    2639115
917                 Autres cantons: autres subventions    2625808
927  Financement de projets de l'UE par le FNS (dès...    1918653
937        Financement de projets de l'UE par le SEFRI    1739988
919  Confédération: contributions liées à des proje...     739396
918  Confédération: contributions aux investissemen...     448785

C’est bien, mais pas très lisible. Si on divisait par mille?

In [51]:
df_GE['UNIGE, en milliers'] = df_GE['GE'] / 1000
df_GE

,Source de financement,GE,"UNIGE, en milliers"
914,Canton universitaire: couverture ou budget,370732623,370732.623
924,Confédération: subventions de base LEHE (autre...,110890055,110890.055
929,Projets du FNS,85110337,85110.337
940,Revenus des prestations de service,80459268,80459.268
916,Autres cantons: accord intercantonal universit...,37795445,37795.445
938,Mandats de recherche du secteur privé,24933883,24933.883
913,Autres moyens propres de la haute école,20205526,20205.526
912,Ecolage,13580478,13580.478
941,Revenus de la formation continue,13551495,13551.495
931,Programmes de recherche de l'UE,12979363,12979.363
933,Mandats de recherche de la Confédération,12662390,12662.390
939,Mandats de recherche des autres collectivités ...,12112604,12112.604
930,Projets de Innosuisse (autrefois CTI),2866273,2866.273
932,Autres programmes internationaux,2639115,2639.115
917,Autres cantons: autres subventions,2625808,2625.808
927,Financement de projets de l'UE par le FNS (dès...,1918653,1918.653
937,Financement de projets de l'UE par le SEFRI,1739988,1739.988
919,Confédération: contributions liées à des proje...,739396,739.396
918,Confédération: contributions aux investissemen...,448785,448.785

Et pour enlever ces décimales? Oui, vous avez déjà vu cette fonction!

In [54]:
df_GE['UNIGE, en milliers'] = round(df_GE['UNIGE, en milliers'])
df_GE

,Source de financement,GE,"UNIGE, en milliers"
914,Canton universitaire: couverture ou budget,370732623,370733.0
924,Confédération: subventions de base LEHE (autre...,110890055,110890.0
929,Projets du FNS,85110337,85110.0
940,Revenus des prestations de service,80459268,80459.0
916,Autres cantons: accord intercantonal universit...,37795445,37795.0
938,Mandats de recherche du secteur privé,24933883,24934.0
913,Autres moyens propres de la haute école,20205526,20206.0
912,Ecolage,13580478,13580.0
941,Revenus de la formation continue,13551495,13551.0
931,Programmes de recherche de l'UE,12979363,12979.0
933,Mandats de recherche de la Confédération,12662390,12662.0
939,Mandats de recherche des autres collectivités ...,12112604,12113.0
930,Projets de Innosuisse (autrefois CTI),2866273,2866.0
932,Autres programmes internationaux,2639115,2639.0
917,Autres cantons: autres subventions,2625808,2626.0
927,Financement de projets de l'UE par le FNS (dès...,1918653,1919.0
937,Financement de projets de l'UE par le SEFRI,1739988,1740.0
919,Confédération: contributions liées à des proje...,739396,739.0
918,Confédération: contributions aux investissemen...,448785,449.0

## Exercice

- Comment a été principalement financée l’Université de Fribourg en 2019?
- Et en 1999?
- Réfléchissez à la structure des données. Est-elle pratique à explorer? Quelle structure vous paraîtrait plus pratique? (Ici, pas besoin de coder bien sûr. Notez vos idées quelque part, par exemple dans le bloc «Structure des données» ci-dessous.)

### Structure des données

[Un endroit où vous pouvez noter des idées]